# Streamlit Secrets Configuration
# Place this file in .streamlit/secrets.toml in your project root

[supabase]
url = "your_supabase_project_url_here"
key = "your_supabase_anon_key_here"

[rentcast]
api_key = "your_rentcast_api_key_here"

