# Streamlit Secrets Configuration
# Place this file in .streamlit/secrets.toml in your project root

RENTCAST_API_KEY = "your_rentcast_api_key"
SUPABASE_URL = "your_supabase_url"
SUPABASE_KEY = "your_supabase_anon_key"
